<?php

namespace KSH\BibeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BabyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BabyRepository extends EntityRepository
{
}
