<?php

namespace KSH\BibeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BiberonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiberonRepository extends EntityRepository
{
	//Nbr de biberon pour le bébé $id et la date $date donnée
	public function findByDateBabyNbBiberons($id, \Datetime $date) {
 
        return $this->createQueryBuilder('a')
 
                        ->select('COUNT(a)')
                        ->andwhere('a.baby = :id')
                        ->andwhere('a.date >= :date_start')
                        ->andwhere('a.date <= :date_end')
                        ->setParameter('id', $id)
                        ->setParameter('date_start', $date->format('Y-m-d 00:00:00'))
                        ->setParameter('date_end',   $date->format('Y-m-d 23:59:59'))

                        ->getQuery()
 
                        ->getSingleScalarResult();
 
    }

    //Date et heure du dernier biberon pour le bébé $id
	public function findByBabyLastBiberon($id) {
		return $this->createQueryBuilder('b')
 
                        ->select('MAX(b.date)')
                        ->where('b.baby = :id')
                        ->setParameter('id', $id)
                        ->groupBy('b.baby')
                        ->orderBy('b.baby', 'DESC')
                        ->setMaxResults(1)

                        ->getQuery() 
                        ->getSingleScalarResult();
	}

    //Nbr de biberons et le volume d'eau par jour pour le bébé $id
    public function findAllByIdBiberonsVolumeDate($id) {
        return $this->createQueryBuilder('c')
  
                        ->select('COUNT(c) as bibis')
                        ->addSelect('SUM(c.waterVolume) as volume')
                        ->addSelect('SUBSTRING(c.date, 1, 4) as year')
                        ->addSelect('SUBSTRING(c.date, 6, 2) as month')
                        ->addSelect('SUBSTRING(c.date, 9, 2) as day')
                        ->andwhere('c.baby = :id')
                        ->setParameter('id', $id)

                        ->groupBy('year, month, day')
                        ->orderBy('c.date', 'ASC')

                

                        
                        ->getQuery()
 
                        ->getArrayResult();
 
    }
}
